<?xml version="1.0" encoding="utf-8"?><Database Name="myshop" Class="productsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ProductStore" Member="ProductStores">
    <Type Name="ProductStore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="productPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>